### ISSUE TITLE
upper_case filter doesnt exists

### ISSUE THREAD

**Issue by jorgeflores** [Wixel/GUMP#224]
Hi,

I tried to use the "upper_case" filter, I'm using 1.5.6 version, but I had the following error:

Details
Type: Exception
Message: Filter method 'upper_case' does not exist.
File: D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\wixel\gump\gump.class.php
Line: 699
Trace
#0 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\wixel\gump\gump.class.php(267): GUMP->filter(Array, Array)
#1 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\src\TravelXite\Services\Impl\ValidationServiceImpl.php(83): GUMP->run(Array)
#2 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\src\routes.php(185): TravelXite\Services\Impl\ValidationServiceImpl->validateInputLead(Array)
#3 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\slim\slim\Slim\Route.php(335): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\slim\slim\Slim\Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\slim\slim\Slim\App.php(495): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\slim\slim\Slim\App.php(388): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\vendor\slim\slim\Slim\App.php(296): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 D:\Proyectos\travelxite\xampp-php7\htdocs\contact-form-api\public\index.php(30): Slim\App->run()
#13 {main}

This is my code:

  $gump = new \GUMP();
  $gump->filter_rules(array(                 
            'currencyisocode' => 'trim|sanitize_string|upper_case',
            'leadsource' => 'trim|sanitize_string',          
            'type' => 'trim|sanitize_string|upper_case',
            'company' => 'trim|sanitize_string'
        ));
  $validated_data = $gump->run($lead);

Thank you.

**Comment by filisko** [comment]
Hi @jorgeflores, I tried your code and it works. Give some more detailed info please
